"""initial tables

Revision ID: d2e9ffd6786f
Revises:
Create Date: 2026-02-01 12:49:10.691767

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d2e9ffd6786f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
